# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoundOfPulsars' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoundOfPulsars
   pod 'AudioKit/Core'


  target 'SoundOfPulsarsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoundOfPulsarsUITests' do
    # Pods for testing
  end

end
